name: ememoink
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  carousel_slider: ^5.1.1
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  get_it: ^9.2.0
  google_sign_in: ^7.2.0
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  oauth2: ^2.0.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/android.png
    - assets/google/android_light_rd_na@4x.png
    - assets/google/android_light_rd_na@1x.png
    - .env